name: "Set up MSSQL"
description: "Setup MSSQL"
branding:
  icon: "database"
  color: "blue"
inputs:
  sa-password:
    description: "SQL Server SA password"
    required: false
    default: "Password@12345!"
  version:
    description: "SQL Server version. This will choose the latest patch version of the specified version. For example, 2022 will use 2022-latest image."
    required: false
    default: "2022"
  user:
    description: "SQL Server user"
    required: false
    default: "test"
  password:
    description: "SQL Server user password"
    required: false
    default: "test"
  database:
    description: "SQL Server database for user if specified"
    required: false
    default: "test"
  port:
    description: "SQL Server port"
    required: false
    default: "1433"
  container-name:
    description: "Container name"
    required: false
    default: "setup_mssql_server"
  image-tag:
    description: "SQL Server image tag. If specified, it will override 'version' input. See more at https://mcr.microsoft.com/v2/mssql/server/tags/list"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        chmod +x ${{ github.action_path }}/install.sh
        ${{ github.action_path }}/install.sh \
          ${{ inputs.version }} \
          ${{ inputs.sa-password }} \
          ${{ inputs.user }} \
          ${{ inputs.password }} \
          ${{ inputs.database }} \
          ${{ inputs.port }} \
          ${{ inputs.container-name }} \
          ${{ inputs.image-tag }}